import tkinter
from tkinter import messagebox
import mysql.connector
win=tkinter.Tk()
wi=win.winfo_screenwidth()
he=win.winfo_screenheight()
print(wi)
print(he)
win.configure(width=wi,height=he,bg="pink")
def show():
    un=t1.get()
    cl=t2.get()
    ta=t3.get()
    en=t4.get()
    ma=t5.get()
    sci=t6.get()
    so=t7.get()
    con=mysql.connector.connect(host="localhost",user="root",password="12345",database="saran")
    print("connection success")
    cur=con.cursor()
    cur.execute("insert into mark values('%s','%s','%s','%s','%s','%s','%s')"%(un,cl,ta,en,ma,sci,so))
    messagebox.showinfo("success",un+" "+cl+" "+ta+" "+en+" "+ma+" "+sci+" "+so)
    con.commit()
    
    clearfun()
def clearfun():
    t1.delete(0,"end")
    t2.delete(0,"end")
    t3.delete(0,"end")
    t4.delete(0,"end")
    t5.delete(0,"end")
    t6.delete(0,"end")
    t7.delete(0,"end")
    t1.focus()
a1=tkinter.Label(win,text="Enter user name :")
a1.place(x=100,y=100)
t1=tkinter.Entry (win)
t1.place(x=250,y=100)
a2=tkinter.Label(win,text="Roll number :")
a2.place(x=100,y=150)
t2=tkinter.Entry(win)
t2.place(x=250,y=150)
a3=tkinter.Label(win,text="Tamil :")
a3.place(x=100,y=200)
t3=tkinter.Entry(win)
t3.place(x=250,y=200)
a4=tkinter.Label(win,text="English:")
a4.place(x=100,y=250)
t4=tkinter.Entry(win)
t4.place(x=250,y=250)
a5=tkinter.Label(win,text="Maths:")
a5.place(x=100,y=300)
t5=tkinter.Entry(win)
t5.place(x=250,y=300)
a6=tkinter.Label(win,text="Science:")
a6.place(x=100,y=350)
t6=tkinter.Entry(win)
t6.place(x=250,y=350)
a7=tkinter.Label(win,text="Social:")
a7.place(x=100,y=400)
t7=tkinter.Entry(win)
t7.place(x=250,y=400)
b1=tkinter.Button(win,text="Click me",command=show)
b1.place(x=300,y=450)

win.mainloop()

